package uji.sistem.sqlserver.model;

import java.time.LocalDateTime;
import lombok.Data;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope("prototype")
@Data
public class ProsesLogLine{
    private Long id;
    private String cmpnycd;
    private String rcvno;
    private String rxArrangementNumber;
    private int processLogCount;
    private String lensRlType;
    private int previousProcessNumber;
    private int previousSubprocessNumber;
    private int currentProcessNumber;
    private int currentSubprocessNumber;
    private String dipLotNumber;
    private String coatLotNumber;
    private String breakageReasonNumber;
    private String breakageResponsibleProcessNumber;
    private String processFlag1;
    private String processFlag2;
    private String processFlag3;
    private String processFlag4;
    private String processFlag5;
    private String processFlag6;
    private String processFlag7;
    private String processFlag8;
    private String processFlag9;
    private String processFlag10;
    private String processFlag11;
    private String processFlag12;
    private String processFlag13;
    private String processFlag14;
    private String processFlag15;
    private String processFlag16;
    private String additionalTreatmentType1;
    private String additionalTreatmentType2;
    private String additionalTreatmentType3;
    private String additionalTreatmentType4;
    private String additionalTreatmentType5;
    private String additionalTreatmentType6;
    private String additionalTreatmentType7;
    private String additionalTreatmentType8;
    private String additionalTreatmentType9;
    private String additionalTreatmentType10;
    private String additionalTreatmentType11;
    private String additionalTreatmentType12;
    private String additionalTreatmentType13;
    private String additionalTreatmentType14;
    private String additionalTreatmentType15;
    private String additionalTreatmentType16;
    private String additionalTreatmentType17;
    private String additionalTreatmentType18;
    private String additionalTreatmentType19;
    private String additionalTreatmentType20;
    private String materialType;
    private String materialFLensCode;
    private String materialFColorCoatCode;
    private String materialFLensName;
    private String materialFLensColor;
    private String materialFLensCoat;
    private String materialFLensCylinderType;
    private String materialFLensSphere;
    private String materialFLensCylinder;
    private String materialFLensAxis;
    private String materialFLensAddition;
    private String materialFLensDiameter;
    private String materialFOPC;
    private String materialSLensCode;
    private String materialSLensName;
    private String materialSLensColor;
    private String materialSLensMaker;
    private String materialSLensNominalBC;
    private String materialSLensDiameter;
    private String materialSLensThicknessType;
    private String materialSLensAddition;
    private String materialSOPC;
    private String materialRLensCode;
    private String materialRColorCoatCode;
    private String materialRLensName;
    private String materialRLensColor;
    private String materialRLensCoat;
    private String materialRLensCylinderType;
    private String materialRLensSphere;
    private String materialRLensCylinder;
    private String materialRLensAxis;
    private String materialRLensAddition;
    private String materialRLensDiameter;
    private LocalDateTime amddate;
}